- name: set openvpn service name - systemd
  set_fact: openvpn_service_name=openvpn@{{openvpn_config_file}}.service

- name: create openvpn config file
  template: >
    src=server.conf.j2
    dest=/etc/openvpn/{{openvpn_config_file}}.conf
    owner=root
    group=root
  notify:
    - restart openvpn

- name: copy openvpn logrotate config file
  copy: >
    src=openvpn_logrotate.conf
    dest=/etc/logrotate.d/openvpn.conf
    owner=root
    group=root
    mode=0400

- name: setup openvpn auto-start & start
  service: >
    name={{openvpn_service_name}}
    enabled=yes
    state=started
