---
# tasks file for openvpn
- name: Uninstall OpenVPN
  include: uninstall.yml
  when: openvpn_uninstall
  tags:
    - uninstall

- name: Install OpenVPN
  include: install.yml
  tags:
    - install

- name: Setup server keys
  include: server_keys.yml
  tags:
    - server_keys
    - server

# ignoreerrors is required for CentOS/RHEL 6
# http://serverfault.com/questions/477718/sysctl-p-etc-sysctl-conf-returns-error
- name: enable ipv4 forwarding
  sysctl: >
    name=net.ipv4.ip_forward
    value=1
    ignoreerrors=yes

- name: Check for firewalld/iptables
  command: firewall-cmd --state
  register: firewalld
  always_run: yes
  changed_when: false  # Never report as changed
  ignore_errors: yes
  tags:
    - firewall

- name: Add port rules (iptables)
  include: iptables.yml
  when: firewalld.rc!=0
  tags:
    - firewall

- name: Add port rules (firewalld)
  include: firewalld.yml
  when: firewalld.rc==0
  tags:
    - firewall

- name: Create openvpn server directories
  file: 
    path='{{item}}'
    state=directory
    owner=root
    group=root
    mode=0700
  with_items:
    - '{{ ssl_capath }}'
    - '{{ ssl_certpath }}'
    - '{{ ssl_keypath }}'
    - '{{ ssl_scriptpath }}'

- name: Generate client configs
  include: client_keys.yml
  when: client is defined
  tags:
    - client_keys
    - client
 
- name: configure OpenVPN
  include: config.yml
  tags:
    - configure
